config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'index#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user || admin_user?
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def admin_user?
      unless current_user && current_user.name == "admin"
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/index_controller.rb
require 'blockchain_info_service'

class IndexController < ApplicationController

  def index
    @rate = BlockChainInfoService.getRate()
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'],
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user?, :only => [:index]
  before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(
        params.require(:user).permit(:bitcoin_de_api_key))
      @user.save
      render :show
    else

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/index.html.erb
<h2>BTC <%=@rate %> €</h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th>TxID</th>
    <th>Quantity</th>
    <th>BoughtAt</th>
    <th>Profit</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
    <li class='nav-item'><%= link_to 'My Profile', user_path(current_user.id), class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Sign out', signout_path, class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', signin_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Bitcoin Explorer", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#CollapsingNavbar" aria-controls="CollapsingNavbar" aria-expanded="false" aria-label="Toggle navigation">
      &#9776;
    </button>
    <div class="collapse navbar-collapse" id="CollapsingNavbar">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bitcoin Explorer" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bitcoin Explorer" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Profile of <%= @user.name if @user.name %></h3>

<hr />

<div class="container">
  <%= form_for(@user) do |f| %>
      <div class="form-group row">
        <%= f.label :bitcoin_de_api_key, "API Key", class: "col-form-label" %>
        <div class="col-4">
          <%= f.text_field :bitcoin_de_api_key, class: 'form-control' %>
        </div>
        <%= f.submit "Update", class: "btn btn-primary" %>
      </div>
      <div class="form-group row">

      </div>
  <% end %>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<!--<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>-->



<table class="table table-striped">
  <thead>
  <tr>
    <th>TxID</th>
    <th>Quantity</th>
    <th>BoughtAt</th>
    <th>Profit</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>